// Keyword whitelist for Southern California locations. We match against
// this instead of a blanket ", CA" check so Bay Area / NorCal postings
// (Sunnyvale, Palo Alto, San Francisco, etc.) from the same companies
// don't slip through.
const SOCAL_KEYWORDS = [
  // Los Angeles County
  "el segundo",
  "hawthorne",
  "los angeles",
  "long beach",
  "torrance",
  "redondo beach",
  "manhattan beach",
  "hermosa beach",
  "gardena",
  "carson",
  "culver city",
  "playa vista",
  "playa del rey",
  "marina del rey",
  "inglewood",
  "compton",
  "lawndale",
  "lomita",
  "rancho palos verdes",
  "palos verdes",
  "san pedro",
  "wilmington",
  "signal hill",
  "cerritos",
  "downey",
  "norwalk",
  "bellflower",
  "paramount",
  "lakewood",
  "pico rivera",
  "whittier",
  "el monte",
  "monterey park",
  "alhambra",
  "pasadena",
  "burbank",
  "glendale",
  "santa monica",
  "venice, ca",
  "north hollywood",
  "van nuys",
  "sherman oaks",
  "woodland hills",
  "encino",
  "canoga park",
  "chatsworth",
  "northridge",
  "sylmar",
  "san fernando",
  "santa clarita",
  "palmdale",
  "lancaster, ca",
  "claremont",
  "pomona",
  "west covina",
  "diamond bar",
  "city of industry",
  "commerce, ca",
  "vernon, ca",
  "huntington park",
  "south gate",
  "bell, ca",
  "bell gardens",
  "maywood",
  "cudahy",
  "hawaiian gardens",
  "artesia",
  "la mirada",
  "hacienda heights",
  "rowland heights",
  // Orange County
  "costa mesa",
  "irvine",
  "santa ana",
  "anaheim",
  "huntington beach",
  "newport beach",
  "orange, ca",
  "tustin",
  "fullerton",
  "garden grove",
  "mission viejo",
  "lake forest, ca",
  "aliso viejo",
  "laguna",
  "san clemente",
  "san juan capistrano",
  "yorba linda",
  "brea",
  "buena park",
  "cypress, ca",
  "fountain valley",
  "westminster, ca",
  "stanton, ca",
  "seal beach",
  "los alamitos",
  "rancho santa margarita",
  "dana point",
  // San Diego County
  "san diego",
  "chula vista",
  "oceanside",
  "carlsbad",
  "escondido",
  "vista, ca",
  "san marcos, ca",
  "el cajon",
  "poway",
  "encinitas",
  "national city",
  "la jolla",
  "solana beach",
  "del mar",
  // Inland Empire (Riverside / San Bernardino counties)
  "riverside, ca",
  "san bernardino",
  "ontario, ca",
  "rancho cucamonga",
  "fontana, ca",
  "moreno valley",
  "corona, ca",
  "temecula",
  "murrieta",
  "chino, ca",
  "chino hills",
  "redlands",
  "victorville",
  "hesperia",
  "palm springs",
  "palm desert",
  "indio, ca",
  // Ventura County
  "oxnard",
  "ventura, ca",
  "camarillo",
  "thousand oaks",
  "simi valley",
  "moorpark",
  // Santa Barbara County / Vandenberg — where these companies actually launch
  "vandenberg",
  "lompoc",
  "santa barbara",
  "goleta",
  // Imperial County
  "el centro",
  "calexico",
  // Generic phrasing some boards use
  "southern california",
  "greater los angeles",
  "socal",
  "so. cal",
];

const SOCAL_PATTERNS = SOCAL_KEYWORDS.map((keyword) => {
  const escaped = keyword.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const expression = escaped.endsWith(", ca")
    ? `${escaped.slice(0, -4)}, (?:ca\\b|california\\b)`
    : `${escaped}\\b`;
  return new RegExp(`\\b${expression}`, "i");
});

export function isSouthernCalifornia(location: string): boolean {
  return SOCAL_PATTERNS.some((pattern) => pattern.test(location));
}
